### ISSUE TITLE
Feature Request: Parse {"Ref":""} sections while validating

### ISSUE THREAD

**Issue by tjpatter** [widdix/aws-cf-checker#1]
It would be awesome if this tool could parse out {"Ref":"xxxxx"} sections while validating CFN templates.  Use case:  A security group that is populated via a CFN parameter...

**Comment by michaelwittig** [comment]
Maybe I don't get you: How can I know something about a parameter value? E.g I have no idea what Ingres rules are defined so I can't validate anything?

Can you provide a example that demonstrates your need?

**Comment by tjpatter** [comment]
The way I envision it, the command itself would have to be modified to allow passing parameters in from the command line.  

This would be very useful in automated deployment pipeline scenarios where we are deploying the same CFN template to multiple AWS accounts / regions, albeit with different parameters that get passed through the pipeline from various upstream sources.

Example:

cf-checker --templateFile ./path/to/template.json --checksFile ./path/to/checks.json --parametersFile ./path/to/parameters.json

In this way something like Jenkins could write out the environment-specific parameters to a temp file that gets passed into the cf-checker.

**Comment by michaelwittig** [comment]
@tjpatter but that still doesn't solve the problem that the script knows nothing about the resource that you pass in as a parameter.

Example:
If you pass in a security group id, cf-checker has no idea what inbound and outbound rules are defined inside that Security Group. 

Do you get my concern? Or what exactly are you trying to check?
